- .github/workflows/pr-auto-assign.yml
Closes #8
- auto-assign-action 워크플로 (`.github/workflows/auto-assign.yml`) 생성
- reviewers 및 assignees 설정용 `.github/auto_assign.yml` 추가
- #8
> ci: PR 자동 리뷰어 및 어싸인 등록 기능 구현

- src/assets/css/global.css
- src/assets/css/variables.css
- src/components/common/SkeletonDetail.vue
- src/components/common/SkeletonItem.vue
- src/components/common/StatusButton.vue
- src/components/common/filters/FilterButtons.vue
- src/components/common/top-actions/CreateButton.vue
- src/components/layout/DetailLayout.vue
- src/components/layout/detailview/DetailTable.vue
- src/components/layout/detailview/DetailTableMoreLink.vue
- src/components/layout/detailview/DetailTablePagination.vue
- src/components/layout/detailview/InfoGroup.vue
- src/components/layout/detailview/InfoItem.vue
- src/constants/dummy/orderDetail.js
- src/features/order/components/OrderDetailBasic.vue
- src/features/order/components/OrderDetailBasicInfo.vue
- src/features/order/components/OrderDetailDate.vue
- src/features/order/components/OrderDetailDeliveryHistory.vue
- src/features/order/components/OrderDetailDetail.vue
- src/features/order/components/OrderDetailFranchise.vue
- src/features/order/components/OrderDetailRejectReason.vue
- src/features/order/components/OrderDetailSummary.vue
- src/features/order/components/OrderTable.vue
- src/features/order/router.js
- src/features/order/views/OrderDetailView.vue
- src/features/order/views/OrderListView.vue
Closes #12
- 상세 조회 전용 공통 레이아웃인 DetailLayout 구현
- props: title, description
- #actions: 상단 우측 액션 버튼 영역
- #basic: 기본 정보 그룹. InfoGroup, InfoItem
- #detail: 상세 테이블 정보
- #footer: 하단 영역(선택적)
- 최상단 섹션 : 제목/설명과 버튼 영역으로, 각 버튼은 StatusButton으로 구현 가능
- 기본 정보 섹션 : 
- InfoGroup 컴포넌트로 각 영역에 대한 그리드 설정. grid-2로 두 개 나열 가능.
- InfoItem 컴포넌트로 각 데이터를 조회. 모든 item은 하나의 label과 N개의 value를 가질 수 있음.
- Skeleton 적용을 하려 했으나 skeleton 적용 이후 값 불러올 때 새로 길이 정렬이 안 맞는 문제로 컴포넌트까지만 만들고 실제 적용은 보류.
- 상세 정보 섹션 : 표 형식으로 상세 정보를 조회할 때 사용하는 영역.
- DetailTable : 기본적인 표 상세 보기
- DetailTableMoreLink : 더보기 버튼을 통해 다른 페이지로 넘어가는 상세 보기
- DetailTablePagination : pagination이 적용된 상세 보기
- 기타 사용성 개선
- 버튼에 대한 공통 컴포넌트인 StatusButton 구현. 버튼 상태에 따른 디자인 자동 설정. 기존의 버튼인 CreateButton, FilterButtons도 이 컴포넌트를 사용하도록 구조 변경함. 
- 상세 조회하는 기능 구현할 때 공통적으로 재사용하기 위한 …
> feat: 상세 조회 페이지를 위한 공통 레이아웃 DetailLayout 구현

- src/components/common/Pagination.vue
Closes #29 
- 페이지네이션 버튼을 페이지가 2개 이상인 경우에 사용할 수 있도록 코드 수정
- 이동 페이지 버튼 중 화살표 1개 버튼은 페이지 1개씩 이동, 화살표 2개 버튼은 10개씩 이동하도록 기능 수정
- #29
> refactor: Pagination 설정 변경

- src/components/common/Pagination.vue
- src/components/layout/Header.vue
- src/components/layout/sidebar/SidebarItemList.vue
- src/constants/sidebarMap.js
- src/features/category/views/CategoryListView.vue
- src/features/member/router.js
Closes #31 
- 메뉴별 기능 설명에 맞는 아이콘 적용
- 메뉴 간 시각적 구분 및 UX 강화
- Font Awesome Free 6.x 기준으로 일관 적용
- #31
> refactor: 사이드바 메뉴 아이콘 적용

- src/features/member/api.js
- src/features/member/master/components/MemberDetailBasic.vue
- src/features/member/master/views/MemberDetailView.vue
- src/features/member/master/views/MemberListView.vue
Closes #33 
- 회원 상세 페이지 회원 정보에서 수정 버튼, 탈퇴 버튼 구현
- 회원 정보 수정, 탈퇴 기능 구현 
- 백엔드 API 연동
- #33
> feat: 회원 정보 수정 기능 구현

- src/features/member/master/views/MemberRegisterView.vue
Closes #53 
- 가맹점/거래처 담당자 회원 등록시
- 연락처(franchiseContact, vendorContact) 숫자만 전송하도록 처리
- 사업자등록번호(franchiseTaxId, vendorTaxId) 하이픈 제거 후 전송
- JSON + 파일을 FormData로 묶어서 전송하는 구조로 변경
- #53
> fix: 가맹점/거래처 담당자 등록 시 연락처·사업자번호 하이픈 제거 및 FormData 전송 구조 통일

- src/features/member/master/components/join/VendorForm.vue
- src/features/member/master/views/MemberRegisterView.vue
Closes #55 
- 거래처 회원 등록이 안되는 문제 해결
- #55
> fix: 거래처 회원 등록이 안되는 문제 해결 

- src/components/common/ConfirmDialog.vue
- src/components/common/RejectReasonDialog.vue
- src/features/requisition/RequisitionApi.js
- src/features/requisition/components/Register/AutoCompleteField.vue
- src/features/requisition/components/Register/RequisitionRegisterOrderInfo.vue
- src/features/requisition/views/RequisitionDetailView.vue
- src/features/requisition/views/RequisitionRegisterView.vue
Closes #57 
- 품의 임시 저장 기능 코드 수정
- 
- #57
> rafactor : 품의 임시 저장 기능 코드 수정

- .github/workflows/s3-cloudfront-deploy.yml
Closes #75 
- AWS IAM 권한 확인 및 GitHub Secrets 등록
- CloudFront 배포 ID 확인 및 설정
- GitHub Actions 워크플로우 작성 및 배포 테스트
- Node.js 22 환경 설정 및 배포 스크립트 작성
- #75
> ci: Vue.js S3 + CloudFront 배포 CI/CD 워크플로우 추가

- src/components/layout/Header.vue
> fix: 코드 수정 

- src/components/common/RejectReasonModal.vue
- src/components/common/fields/DatePickerField.vue
- src/features/category/views/CategoryCreateView.vue
- src/features/purchase/PurchaseApi.js
- src/features/purchase/components/PurchaseFilters.vue
- src/features/purchase/views/PurchaseOrderDetailView.vue
- src/features/purchase/views/PurchaseOrderListView.vue
- src/features/requisition/RequisitionApi.js
- src/features/requisition/components/Register/RequisitionRegisterFooter.vue
- src/features/requisition/components/Register/RequisitionRegisterOrderInfo.vue
- src/features/requisition/components/Register/RequisitionRegisterRightPanel.vue
- src/features/requisition/router.js
- src/features/requisition/views/RequisitionDetailView.vue
- src/features/requisition/views/RequisitionListView.vue
- src/features/requisition/views/RequisitionRegisterView.vue
- src/main.js
Closes #83 
- 품의 / 발주 추가 기능 마무리
- #83
> refactor : 품의 / 발주 추가 기능 마무리

- src/api/axios.js
- src/features/statistics/components/DisposalDashboard.vue
- src/features/statistics/components/InventoryTornoverDashboard.vue
- src/features/statistics/components/MenuSalesDashboard.vue
- src/features/statistics/components/PurchaseOrderDashboard.vue
- src/features/statistics/components/TotalSalesDashboard.vue
Closes #112 
- 차트 랜더링 오류 수정
- #112
> fix: 차트 랜더링 오류 수정

- src/features/order/components/modal/OrderApproveModal.vue
- src/features/order/components/modal/OrderRejectModal.vue
- src/features/order/views/OrderDetailView.vue
- src/features/order/views/OrderListView.vue
- src/features/order/views/OrderRegisterView.vue
- src/features/takeback/components/TakeBackList.vue
Closes #67
- alert를 토스트로 변경
- 불필요한 콘솔 로그 제거
- #67
> feat: 주문에 대한 시각적 요소 개선

- src/components/layout/Header.vue
- src/features/disposal/views/AdminDisposalView.vue
- src/features/disposal/views/DisposalRegisterView.vue
- src/features/order/components/registerview/OrderRegisterOrderInfo.vue
- src/features/order/components/registerview/OrderRegisterVendorSearch.vue
- src/features/purchase/components/PurchaseFilters.vue
- src/features/purchase/views/PurchaseOrderDetailView.vue
- src/features/takeback/components/TakeBackList.vue
- src/features/vendor/components/VendorFilters.vue
- src/features/vendor/views/VendorDetailView.vue
- src/features/vendor/views/VendorListView.vue
- src/features/warehouse/views/InventoryWarehouseView.vue
Closes #119 
- 불필요한 console.log() 삭제
- #119
> refactor: 불필요한 코드 삭제

- src/api/axios.js
- src/features/takeback/api.js
- src/features/takeback/components/TakeBackFilter.vue
- src/features/takeback/components/TakeBackList.vue
- src/features/takeback/views/TakeBackListView.vue
Closes #121 
- 반품 목록 조회
- #121
> fix: 반품 목록 조회

- src/api/axios.js
- src/constants/sidebarMap.js
- src/features/delivery/components/modal/DeliveryStartModal.vue
- src/features/delivery/views/DeliveryDetailView.vue
- src/features/takeback/components/TakeBackMyList.vue
- src/features/takeback/views/TakeBackMyListView.vue
- src/features/warehouse/components/InventoryFilter.vue
- src/features/warehouse/components/InventoryWarehouseFilter.vue
Closes #127 
- 슈퍼 계정 반품 조회 2개 발생하는 문제 해결
- #127
> fix: 슈퍼 계정 반품 조회 2개 발생하는 문제 해결

- src/api/axios.js
Closes #129 
- console.log 주석 처리
- #129
> fix: console.log 주석 처리

- src/constants/sidebarMap.js
- src/features/purchase/views/PurchaseOrderListView.vue
Closes #131
-  드롭다운, 사이드바 수정
- #131
> fix: 드롭다운, 사이드바 수정

- src/constants/sidebarMap.js
- src/features/statistics/components/InventoryTornoverDashboard.vue
- src/features/warehouse/components/InventoryDetailModal.vue
- src/features/warehouse/components/InventoryTable.vue
- src/features/warehouse/views/InventoryView.vue
Closes #133 
- 창고 목록 조회와 재고 상세 모달에 안전재고 추가
- #133
> fix: 창고 목록 조회와 재고 상세 모달에 안전재고 추가

- src/features/contract/components/ContractForm.vue
- src/features/contract/components/ContractTable.vue
- src/features/contract/views/ContractCreateView.vue
- src/features/contract/views/ContractListView.vue
- src/features/product/components/ProductFilters.vue
- src/features/product/components/ProductTable.vue
- src/features/product/views/ProductCreateView.vue
- src/features/product/views/ProductDetailView.vue
- src/features/vendor/views/VendorDetailView.vue
Closes #135 
- 제품 및 거래처별 제품 계약 영문 → 한글 라벨 변경
- 거래처 상세 페이지에 권한 기반 수정 버튼 노출 조건 적용
- #135
> 제품 및 거래처별 제품 계약 영문 → 한글 라벨 변경, 거래처 상세 페이지에 권한 기반 수정 버튼 노출 조건 적용

- src/features/takeback/views/TakeBackDetailView.vue
Closes #137 
- 반품 신청 기능이 미완료 되어 반품 상세 화면에서 증빙 이미지 관련 코드를 주석 처리
- #137
> refactor: 반품 증빙 자료 코드 주석 처리

- src/api/axios.js
- src/features/statistics/components/PredictionAccuracyDashboard.vue
Closes #139 
- prediction_type에 일치하게 predictionType 수정
- #139
> fix: prediction_type에 일치하게 predictionType 수정

- src/features/vendor/components/VendorFilters.vue
- src/features/vendor/components/VendorTable.vue
Closes #144 
- 영문 → 한글 라벨 변경
- #144
> fix: 영문 → 한글 라벨 변경
